const countryDetails = [
  { country: "IN", countryName: "India", countryCode: "+91" },
  { country: "US", countryName: "United States", countryCode: "+1" },
  { country: "CA", countryName: "Canada", countryCode: "+1" },
  { country: "GB", countryName: "United Kingdom", countryCode: "+44" },
  { country: "AU", countryName: "Australia", countryCode: "+61" },
  { country: "AT", countryName: "Austria", countryCode: "+43" },
  { country: "BS", countryName: "Bahamas", countryCode: "+1" },
  { country: "BR", countryName: "Brazil", countryCode: "+55" },
  { country: "BG", countryName: "Bulgaria", countryCode: "+359" },
  { country: "CN", countryName: "China", countryCode: "+86" },
  { country: "DK", countryName: "Denmark", countryCode: "+45" },
  { country: "FI", countryName: "Finland", countryCode: "+358" },
  { country: "FR", countryName: "France", countryCode: "+33" },
  { country: "DE", countryName: "Germany", countryCode: "+49" },
  { country: "HK", countryName: "Hong Kong", countryCode: "+852" },
  { country: "IE", countryName: "Ireland", countryCode: "+353" },
  { country: "IL", countryName: "Israel", countryCode: "+972" },
  { country: "IT", countryName: "Italy", countryCode: "+39" },
  { country: "JP", countryName: "Japan", countryCode: "+81" },
  { country: "LI", countryName: "Lichtenstein", countryCode: "+423" },
  { country: "LT", countryName: "Lithuania", countryCode: "+370" },
  { country: "MX", countryName: "Mexico", countryCode: "+52" },
  { country: "NL", countryName: "Netherlands", countryCode: "+31" },
  { country: "NZ", countryName: "New Zealand", countryCode: "+64" },
  { country: "RO", countryName: "Romania", countryCode: "+40" },
  { country: "SG", countryName: "Singapore", countryCode: "+65" },
  { country: "ZA", countryName: "South Africa", countryCode: "+27" },
  { country: "KR", countryName: "South Korea", countryCode: "+82" },
  { country: "SE", countryName: "Sweden", countryCode: "+46" },
  { country: "CH", countryName: "Switzerland", countryCode: "+41" },
  { country: "TH", countryName: "Thailand", countryCode: "+66" },
  {
    country: "AE",
    countryName: "United Arab Emirates",
    countryCode: "+971",
  },
  { country: "ES", countryName: "Spain", countryCode: "+34" },
];

export default countryDetails;
